### ISSUE TITLE
h2o backend mode reported number of allowed cores != number reported by yarn

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#625] opened 2018-03-19 03:21 UTC
h2o backend mode reported number of allowed cores doesn't match number of vcores reported by yarn.

When created h2o cluster in "backend mode" for Sparkling Water as 

```
hadoop jar $H2O_EXTENDED_JAR -jobname "H2O external cluster for svc_h2oprd" \
				-nodes 160 -mapperXmx 5g -timeout 300 \
				-baseport 33099 -ea -disown 
```

and connected to it from pySpark, it reports as it could use all cores in the cluster
![image](https://user-images.githubusercontent.com/3013418/37576292-5bec0606-2af1-11e8-9376-e13c31edc6f8.png)

Actual number of vcores reported by YARN for this backend h2o cluster is 160 (it thinks that h2o thinks it could use up to 1 vcores for each of the containers).

Then, when I created the same h2o backend cluster, but this time specified `-nthreads 4`, h2o cluster reports now it has `H2O cluster allowed cores:  640` (160 times 4 obviously). 
But again, YARN thinks that h2o application has exact same number of vcores, `160`.

It seems there is a bug in h2o extended jar - it doesn't communicate `-nthreads` to yarn at all. YARN always assumes each container has 1 vcores, which is not what h2o application will use /reports. 

Using latest SW / H2O. Any ideas how to fix this?

**Comment by Tagar** [comment] 2018-03-19 03:44
I tried to specify `-nthreads 4` so h2o per container thread count would match what yarn assumes, but h2o fails to start and reports `4` is the minimum.

It would be best if h2o would correctly report to yarn its intention to use `-nthreads 4` (yarn vcores=4), so YARN resource management is not broken when we try to use h2o "backend" mode.

**Comment by jakubhava** [comment] 2018-03-19 08:19
This is related to just H2O and extended h2o jar and sparkling water is not affecting this. Even though the yarn is using 1 vcore, it can physically use let's say 24 cores underneath. Linux kernel seems to be the source of truth for configuring the cores(compared to memory, which is definitely yarn).

So this is actually not a bug, but behaves as it should - we report number of real cores we use, but do not worry - it is still running inside a container.

Based on our discussion here - https://groups.google.com/forum/#!msg/h2ostream/FZ9ReVFYxYs/gwDSlw3kLwAJ. It relates to Sparkling Water, but the outcome is the same

**Comment by Tagar** [comment] 2018-03-19 14:42
@jakubhava thanks for pointing to that discussion! I just read this and see h2o's point 

Although as @tomkraljevic has pointed out, 

> one could argue that in the sparkling water context, the “executor-threads” setting should propagate automatically to the h2o concept of nthreads.  behavior-wise, i think that would have accomplished what you expected.  that’s a good question and worth a discussion.  (i’m not sure why it’s not like that now…)

Number of vcores could have been propagated to h2o context (or at least would be great to make this configurable if somebody prefers current behavior). Although I do see your point now.

This is a multi-tenant environment, and if we would like application to follow number of "vcores" that yarn cluster has as otherwise h2o job could have severely impacted other jobs' performance. And yes we have cgroups enabled for YARN, so it seems h2o shouldn't take over more cores that it was assigned for. Although not sure how this impacts h2o - when it thinks it has tens of threads (some of our hadoop servers have 44 cores/88 threads) and it actually gets just one (1)?

It gets worse when we have yarn created multiple h2o containers on the same host. So then all those available threads on a servers get counted 3,4 or five times. Our servers have a lot of memory (512Gb) and most of it is available for YARN applications. This is definitely more than a single jvm can handle. So we would prefer to have multiple h2o containers running on same server. I see this was partially discussed on that email chain, but I don't think it covers this aspect too. 

Thank you!

**Comment by jakubhava** [comment] 2020-02-06 07:25
Closing this issue for now

**Closed by jakubhava** 2020-02-06 07:25 UTC
