### ISSUE TITLE
CVE exposed via  `ai.h2o:h2o-genmodel@3.42.0.2 › no.priv.garshol.duke:duke@1.2 `

### ISSUE THREAD

**Issue by jakubhava** [h2oai/sparkling-water#5654] opened 2023-08-03 20:48 UTC
<img width="1235" alt="Screenshot 2023-08-03 at 22 47 18" src="https://github.com/h2oai/sparkling-water/assets/4374603/89dbba16-8524-426f-975c-b4f446312b61">

cc @wendycwong @mn-mikke

**Comment by mn-mikke** [comment] 2023-08-15 10:24
This issue will be covered by https://github.com/h2oai/h2o-3/issues/15687

**Comment by mn-mikke** [comment] 2023-09-07 12:12
The problem is fixed in the SW version `3.42.0.3-1`.

**Closed by mn-mikke** 2023-09-07 12:12 UTC
