### ISSUE TITLE
Running Aggregator results in lost Spark/SW executors

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#519] opened 2018-01-02 16:23 UTC
Hello,

Running Aggregator model on ~80M records is completing fine. 

Running the same model on ~12B records results in executors being lost.

How we can add some diagnostics here? 

We have plenty of executors for such a dataset and each executor has a lot of memory.

CDH 5.12.1

**Comment by jakubhava** [comment] 2018-01-02 16:27
Hi @Tagar,
 what version of Sparkling Water & Spark are you using please ? I would suggest looking into yarn logs first to see what happened there or you can share the log files here. You should be able to get the yarn logs as
`yarn logs -applicationId <application ID>`

Executor usually gets lost because of the memory issues or dynamic allocation so would be good to see the logs to eliminate these 2 simple causes.

Thanks,
Kuba

**Comment by Tagar** [comment] 2018-01-02 17:49
@jakubhava thanks for prompt response, we're still using that specially built SW you provided us for issue described in https://github.com/h2oai/sparkling-water/issues/485

I did check Spark driver log, and it read executor lost messages. I will give it another try and see if there's anything suspicious can be spotted in yarn logs - will check again.

**Comment by jakubhava** [comment] 2018-01-02 19:34
Thanks @Tagar !

It would be good to find out what is the root cause for the executors going down.

**Comment by jakubhava** [comment] 2018-01-22 12:35
Hi @Tagar, any updates on this, please ?

**Comment by Tagar** [comment] 2018-01-22 14:56
@jakubhava we managed Aggregator to complete using many more executors than we thought necessary for that dataset (12 billion records, 6 features).

It took under 5 hours using 50 executors on 200 vcores. Each executor had 17Gb of memory. 

I had no time to try to rerun that again using fewer executors again..

**Comment by jakubhava** [comment] 2018-01-23 08:38
Oki, let me close this issue for now. Please feel free to reopen it or close if it happens again

**Closed by jakubhava** 2018-01-23 08:38 UTC
