### ISSUE TITLE
ERROR ai.h2o.sparkling.ml.utils.Utils  - Reading a mojo model with metadata failed.

### ISSUE THREAD

**Issue by monkey408** [h2oai/sparkling-water#2512] opened 2021-04-23 08:56 UTC
Hi, When i use H2OAutoML to fit a dataset, then there occurs an error like this:
`[main] ERROR ai.h2o.sparkling.ml.utils.Utils  - Reading a mojo model with metadata failed. Trying to load the model without metadata...
java.lang.IllegalStateException: Model 'XGBoost_3_AutoML_20210423_154521' is expected to have has non-standard number of columns.
	at hex.genmodel.algos.ensemble.StackedEnsembleMojoReader.createMapping(StackedEnsembleMojoReader.java:49)
	at hex.genmodel.algos.ensemble.StackedEnsembleMojoReader.readParentModelData(StackedEnsembleMojoReader.java:34)
	at hex.genmodel.MultiModelMojoReader.readModelData(MultiModelMojoReader.java:24)
	at hex.genmodel.ModelMojoReader.readAll(ModelMojoReader.java:239)
	at hex.genmodel.ModelMojoReader.readFrom(ModelMojoReader.java:65)
	at ai.h2o.sparkling.ml.utils.Utils$.getMojoModel(Utils.scala:31)
	at ai.h2o.sparkling.ml.models.H2OMOJOModel$.createFromMojo(H2OMOJOModel.scala:256)
	at ai.h2o.sparkling.ml.internals.H2OModel.toMOJOModel(H2OModel.scala:55)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.fit(H2OAutoML.scala:97)`
And, i use H2OGBM and H2ODeepLearning and the other simple model method to fit the same dataset, it can success.
I think there is some problem with my dataset . 
So, can you give me some suggest to solve this problem ?

**Comment by mn-mikke** [comment] 2021-04-23 09:47
Hi @monkey408,
What version of SW do you use?

Such a error is thrown if SW fails to deserialize MOJO Model with training metadata. The metadata are used just for `getter` methods of `H2OMOJOModel` to get actual values of training parameters. [If the deserialization with metadata fails, SW tries to deserialize the model without metadata and you will get a model that can be used for model scoring.](https://github.com/h2oai/sparkling-water/blob/01fcdeca9392d8d682681a3e9a952526818fefe7/scoring/src/main/scala/ai/h2o/sparkling/ml/utils/Utils.scala#L34)

Is this your case? Does the fit method return a model? Or it fails completely?

 cc @michalkurka @ledell  @sebhrusen @tomasfryda

**Comment by michalkurka** [comment] 2021-04-23 16:46
> Model 'XGBoost_3_AutoML_20210423_154521' is expected to have has non-standard number of columns.

It looks like a bug in the Stacked Ensembles Mojo. This confusingly worded message means is produced if the SE meta learner doesn't see the same number of columns in one of the submodels.

I do think I see the bug in the code, however, it would help us a lot if you could provide us with the MOJO you are using.

**Comment by michalkurka** [comment] 2021-04-23 18:30
I can confirm this is a bug in H2O: https://h2oai.atlassian.net/browse/PUBDEV-8120
A test that demonstrates the issue: https://github.com/h2oai/h2o-3/pull/5455/files#diff-c9f22519f880745e5ee899b2f8b58f9de4e373e38598755b6f6a128142881ad5R1598

**Comment by monkey408** [comment] 2021-04-26 06:28
Hi @mn-mikke @michalkurka 
The version of SW is '3.32.1.1-1-2.4', and last time the fit method fails completely.
And I change the code as #5455, then I test again, this time the error message is :
`ERROR ai.h2o.sparkling.ml.utils.Utils  - Reading a mojo model with metadata failed. Trying to load the model without metadata...
java.lang.IllegalStateException: Model 'XGBoost_grid__1_AutoML_20210425_173547_model_23' does not have input column 'a50'
	at hex.genmodel.algos.ensemble.StackedEnsembleMojoReader.createMapping(StackedEnsembleMojoReader.java:62)
	at hex.genmodel.algos.ensemble.StackedEnsembleMojoReader.readParentModelData(StackedEnsembleMojoReader.java:34)
	at hex.genmodel.MultiModelMojoReader.readModelData(MultiModelMojoReader.java:24)
	at hex.genmodel.ModelMojoReader.readAll(ModelMojoReader.java:239)
	at hex.genmodel.ModelMojoReader.readFrom(ModelMojoReader.java:65)
	at ai.h2o.sparkling.ml.utils.Utils$.getMojoModel(Utils.scala:31)
	at ai.h2o.sparkling.ml.models.H2OMOJOModel$.createFromMojo(H2OMOJOModel.scala:256)
	at ai.h2o.sparkling.ml.internals.H2OModel.toMOJOModel(H2OModel.scala:55)
	at ai.h2o.sparkling.ml.algos.H2OAutoML.fit(H2OAutoML.scala:97)`
I figure out this column 'a50': only 1164 rows are not null in all of 15432 rows. So I fill the missing value of this column firstly, then I run the 'fit' method again, finally it runs successfully.
So, is it necessary to fill the missing value before automl.fit() method ?

**Comment by ledell** [comment] 2021-07-17 06:01
@mn-mikke @michalkurka Hey there, was this issue resolved by https://github.com/h2oai/h2o-3/pull/5455?
Just noticed that this issue is still open.

**Comment by mn-mikke** [comment] 2021-07-19 14:50
Hi @monkey408,
Can you upgrade to SW `3.32.1.4-1` and confirm that the issue was resolved? 

@erin Thanks for reminding us!

**Comment by mn-mikke** [comment] 2021-07-29 16:38
@monkey408, I'm closing the issue. In case the problems is still there, please reopen the ticket. Thank you!

**Closed by mn-mikke** 2021-07-29 16:38 UTC
