### ISSUE TITLE
cannot start pysparkling

### ISSUE THREAD

**Issue by yx77030** [h2oai/sparkling-water#154] opened 2016-12-13 06:02 UTC
trying pysparkling in CDH5.8, using sparkling-water 1.6.8
when I ran 
from pysparkling import * 
hc = H2OContext.getOrCreate(sc)

I got error:
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-e2156cb48bbf> in <module>()
      1 from pysparkling import *
----> 2 hc = H2OContext.getOrCreate(sc)

/tmp/cloudera/spark/work/spark-f3fffd6e-0906-45c4-a4d3-4bb2008d6e46/userFiles-f3934596-ade2-43ff-b59a-642c416f5ae2/h2o_pysparkling_1.6-1.6.8-py2.7.egg/pysparkling/context.pyc in getOrCreate(spark_context, conf)
    126             selected_conf = H2OConf(spark_context)
    127         method_params[1] = selected_conf._jconf
--> 128         jhc = method.invoke(None, method_params)
    129         h2o_context._jhc = jhc
    130         h2o_context._conf = selected_conf

/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py in __call__(self, *args)
    811         answer = self.gateway_client.send_command(command)
    812         return_value = get_return_value(
--> 813             answer, self.gateway_client, self.target_id, self.name)
    814 
    815         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/usr/lib/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    306                 raise Py4JJavaError(
    307                     "An error occurred while calling {0}{1}{2}.\n".
--> 308                     format(target_id, ".", name), value)
    309             else:
    310                 raise Py4JError(

Py4JJavaError: An error occurred while calling o74.invoke.
: java.lang.AbstractMethodError
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.log(InternalH2OBackend.scala:31)
	at org.apache.spark.Logging$class.logWarning(Logging.scala:70)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.logWarning(InternalH2OBackend.scala:31)
	at org.apache.spark.h2o.backends.SharedBackendUtils$class.checkAndUpdateConf(SharedBackendUtils.scala:54)
	at org.apache.spark.h2o.backends.internal.InternalH2OBackend.checkAndUpdateConf(InternalH2OBackend.scala:40)
	at org.apache.spark.h2o.H2OContext.<init>(H2OContext.scala:83)
	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:262)
	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yx77030** [comment] 2016-12-13 23:19
the above error occurred when Python 2 kernel was used.
when Python 3 was used, got the following error:
File "/tmp/cloudera/spark/work/spark-1cd74207-cb5e-4a85-a816-aed0d32d68b3/userFiles-64ed98ac-0156-4fc7-86f7-2d94f9bf1d7e/h2o_pysparkling_1.6-1.6.8-py2.7.egg/pysparkling/context.py", line 152
    print self
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by mdymczyk** [comment] 2016-12-19 06:59
@yx77030 yes Python3 won't work with 1.6.x branch for now, if you want to try Python3 please use SW 2.0.2.

We'll look into your original problem with Python2.

**Comment by mdymczyk** [comment] 2017-01-24 08:00
Duplicate of #127 fix pushed but not yet released.

**Closed by mdymczyk** 2017-01-24 08:00 UTC
