### ISSUE TITLE
java.lang.ClassNotFoundException: ai.h2o.sparkling.ml.models.H2OSupervisedMOJOModel

### ISSUE THREAD

**Issue by manujchandra** [h2oai/sparkling-water#1974] opened 2020-03-21 06:21 UTC
Hi!,

I am running a local PySpark cluster. 
 
Versions:
Spark : v2.4.5
PySparkling 2.4
Python 3.6.10 :: Anaconda

I did a small SMS spam ham classification model. I am trying to deploy the model as instructed [here](https://github.com/h2oai/h2o-tutorials/blob/master/training/sparkling_water_hands_on/sentiment_analysis/AmazonFineFoodPipeline.ipynb) is the "Let's Deply the Application" section

When loading the model, I get the following error:

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-53b9ea9fab97> in <module>
      1 # load the exported pipeline model
      2 from pyspark.ml import PipelineModel
----> 3 pipeline_model = PipelineModel.load("spam_or_ham.model/")

~/anaconda3/envs/spark/lib/python3.6/site-packages/pyspark/ml/util.py in load(cls, path)
    360     def load(cls, path):
    361         """Reads an ML instance from the input path, a shortcut of `read().load(path)`."""
--> 362         return cls.read().load(path)
    363 
    364 

~/anaconda3/envs/spark/lib/python3.6/site-packages/pyspark/ml/pipeline.py in load(self, path)
    240         metadata = DefaultParamsReader.loadMetadata(path, self.sc)
    241         if 'language' not in metadata['paramMap'] or metadata['paramMap']['language'] != 'Python':
--> 242             return JavaMLReader(self.cls).load(path)
    243         else:
    244             uid, stages = PipelineSharedReadWrite.load(metadata, self.sc, path)

~/anaconda3/envs/spark/lib/python3.6/site-packages/pyspark/ml/util.py in load(self, path)
    298         if not isinstance(path, basestring):
    299             raise TypeError("path should be a basestring, got type %s" % type(path))
--> 300         java_obj = self._jread.load(path)
    301         if not hasattr(self._clazz, "_from_java"):
    302             raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"

~/anaconda3/envs/spark/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

~/anaconda3/envs/spark/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~/anaconda3/envs/spark/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o40.load.
: java.lang.ClassNotFoundException: ai.h2o.sparkling.ml.models.H2OSupervisedMOJOModel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:651)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
	at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
```

Code is:

```python
from pyspark import SparkContext

from pysparkling import *
from pysparkling.ml import *

from pyspark.sql import SQLContext
from pyspark.sql.types import StructType



import json
import os
```

```python
sc = SparkContext("local[*]", "spamorham")
```

```python
# check we have spark available
sc
```

```python
sqlContext = SQLContext(sc)
```

```python
# load the exported pipeline model
from pyspark.ml import PipelineModel
pipeline_model = PipelineModel.load("spam_or_ham.model/")
```

```python

```

```python
schema = StructType.fromJson(json.load(open("schema.json", "r")))
```

```python
print(schema)
```

```python
# Start Streaming
from subprocess import Popen
Popen(["./start_streaming.sh"])
```

```python
!ls output
```

```python

```

```python
input_data_stream = sqlContext.readStream.schema(schema).csv("output")
```

```python
output_data_stream = pipeline_model.transform(input_data_stream)
```

```python
# store in memory. Can also store in bucket or another stream
output_data_stream.writeStream.format("memory").queryName("label").start()
```

```python
import time
while(True):
    sqlContext.sql("select * from label").show()
    time.sleep(5)
```

Note: I have tried in Python 3.7 also with same error. 
Tried on a fresh conda environment as well.

**Comment by jakubhava** [comment] 2020-03-21 06:53
@manujchandra What PySparkling version are you please using? Would it be possible to share the pipeline model with us?

**Comment by manujchandra** [comment] 2020-03-21 07:29
Hi @jakubhava ,

PySparkling was installed using the following command in conda:
`pip install h2o-pysparkling-2.4`

pip list shows:
`h2o-pysparkling-2.4                3.28.1.2.post1`

Please find the complete modeling and scoring pipeline attached:

[PYSPARKLING ERROR.zip](https://github.com/h2oai/sparkling-water/files/4362555/PYSPARKLING.ERROR.zip)

Regards.

**Comment by jakubhava** [comment] 2020-03-21 07:39
Thank you, the pipeline seems to be fine -> Also I see that you are installing PySparkling actually from PiPy, not from Conda is that correct?

Did you modify the Spark Classpath or added any extra jars, for example sparkling water jar?

**Comment by jakubhava** [comment] 2020-03-21 07:44
Ah, sorry. I see where is the problem. 

Can you please run 
```
from pysparkling.initializer import Initializer
Initializer.load_sparkling_jar()
```
At the beginning of the scoring code? We need to explicitly load SW assembly jar to spark env.

Please let me know whether this worked.

**Comment by manujchandra** [comment] 2020-03-21 07:49
Hi @jakubhava ,

If I remember correctly, I tried using [conda](https://anaconda.org/h2oai/h2o_pysparkling_2.2) but it had an old version of pysparkling (2.2). Also when attempting to install it got stuck and was unable to resolve the environment. So I tried a fresh environment with pip as mentioned in the [docs](http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/pysparkling.html)

On a side note, only `pip install h2o` works in my conda. `conda install -c anaconda h2o` does not work.

> Did you modify the Spark Classpath or added any extra jars, for example sparkling water jar?
No. I did not.

**Comment by manujchandra** [comment] 2020-03-21 08:02
Hi @jakubhava ,

I tried all 3 combinations:

`import pysparkling`

and

```
from pysparkling.initializer import Initialize
Initializer.load_sparkling_jar()
```

and 

```
import pysparkling
from pysparkling.initializer import Initializer
Initializer.load_sparkling_jar()
```

All 3 did not work. Notebook attached:

[Model Deployment.zip](https://github.com/h2oai/sparkling-water/files/4362568/Model.Deployment.zip)

**Comment by manujchandra** [comment] 2020-03-22 07:25
Hi @jakubhava ,

I finally managed to execute `PipelineModel.load`. Here is the strange part:

First execute 

```
import pysparkling.ml
from pysparkling.initializer import Initializer
Initializer.load_sparkling_jar()
```

Then run `PipelineModel.load` . It will throw the error.

Then again execute 

```
import pysparkling.ml
from pysparkling.initializer import Initializer
Initializer.load_sparkling_jar()
```

Then run `PipelineModel.load` . It will work. So the imports need to be run two times.

But now there is another problem. The output from `sqlContext.sql("select * from predictions").show()` is empty even though there are files in the output directory.

Any ideas? Thanks.

Here is the code:

[scoring.zip](https://github.com/h2oai/sparkling-water/files/4364805/scoring.zip)

**Comment by jakubhava** [comment] 2020-03-22 07:44
Thank you for the info!, I will try to reproduce at the start of this week.

**Comment by jakubhava** [comment] 2020-04-01 01:03
@manujchandra sorry for delay.

I was able to reproduce something similar,  can you please verify it is your case?

```
import pysparkling.ml
from pyspark.sql import SparkSession

# Initiate SparkSession
spark = SparkSession.builder.appName("App name").getOrCreate()

from pyspark.ml import PipelineModel
pipeline_model = PipelineModel.load("/Users/kuba/Desktop/spam_or_ham.model/")
```
This fails, but:
```

from pyspark.sql import SparkSession

# Initiate SparkSession
spark = SparkSession.builder.appName("App name").getOrCreate()
import pysparkling.ml
from pyspark.ml import PipelineModel
pipeline_model = PipelineModel.load("/Users/kuba/Desktop/spam_or_ham.model/")
```

Works. The important part is that the import `import pysparkling.ml` needs to be after spark/spark context initialization.

If that is your case, please put the import after `sc` creation. I will try to work on a fix in the meanwhile

**Comment by jakubhava** [comment] 2020-04-01 03:03
I believe this should fix the issue you're having https://github.com/h2oai/sparkling-water/pull/2011

After this change, you just need to call `import pysparkling` at the top of your script

**Comment by jakubhava** [comment] 2020-04-03 02:08
Closing as we have a fix, it's going into the next fix release

**Closed by jakubhava** 2020-04-03 02:08 UTC
