### ISSUE TITLE
`as_h2o_frame` limited to 100 columns?

### ISSUE THREAD

**Issue by willfrey** [h2oai/sparkling-water#543] opened 2018-01-23 03:12 UTC
I'm trying to convert a PySpark dataframe with >100 columns into an H2O frame. The resulting H2O frame only has 100 of the original source columns.

I'm using PySpark 2.2.0, H2O 3.16.0.4, and pysparkling 2.2.7.

Here's a minimal example, assuming that `hc` is your `pysparkling.H2OContext` object and `spark` is your `pyspark.sql.SparkSession` object:

```python
data = [tuple(range(150)) for _ in range(2)]
columns = ['_{}'.format(i) for i in data[0]]
dataframe = spark.createDataFrame(data, columns)
h2oframe = hc.as_h2o_frame(dataframe)
assert len(dataframe.columns) == len(h2oframe.columns)  # this will fail
```

What is going on here?

**Comment by jakubhava** [comment] 2018-01-23 08:47
Ho @willfrey, thanks for reporting.

Internally the whole frame is being processed, however, just for the optimization purposes, we sent only 100 first columns to the client - those are the columns you see returned by `h2oframe.columns`

If you invoke any future operation on the frame, it will be again invoked on all the columns. To get number of columns in the full backing frame, you can use `h2oframe.ncols`

**Comment by willfrey** [comment] 2018-01-23 14:34
Thank you for the quick response!

Columns are being reported as missing if I try to use my H2O frame to train an H2O estimator, `h2o.estimstors.gbm.H2OGradientBoostingEstimator` in my particular case.

What is the best way to force the H2O frame to populate all the columns so that I may use it for model training?

**Comment by jakubhava** [comment] 2018-01-23 15:42
Currently, there is no public API to change the default number of cached columns on the client - however, it's easy to expose it.

But it seems like a bug that `h2o.estimstors.gbm.H2OGradientBoostingEstimator` is using only a portion of columns instead of all available in the backing frame.

Could you please share the minimal code which can reproduce this issue so I could look into it?

That would help a lot! Thanks

**Comment by willfrey** [comment] 2018-01-23 18:12
Sorry for the delay! This should do the trick.

```python
import random

from h2o.estimators.gbm import H2OGradientBoostingEstimator
from pyspark.sql import SparkSession
from pysparkling import H2OContext

seed = 1
random.seed(seed)
spark = SparkSession.builder.getOrCreate()
hc = H2OContext.getOrCreate(spark)
# This will make a dataframe with 10 rows, each with 101 elements.
# Each row has 100 predictors and a single response variable.
num_predictors = 100
data = []
for _ in range(10):
    predictors = [random.random() for _ in range(num_predictors)]
    response = random.choice([0, 1])
    row = predictors + [response]  # Each row has 101 elements.
    data.append(row)
predictor_columns = ['predictor_{}'.format(i) for i in range(num_predictors)]
response_column = 'response'
columns = predictor_columns + [response_column]
dataframe = spark.createDataFrame(data, schema=columns)
h2oframe = hc.as_h2o_frame(dataframe)
training_frame, validation_frame = h2oframe.split_frame([0.7], seed=seed)
gbm = H2OGradientBoostingEstimator(seed=seed)
# The next call should raise:
# >>> H2OValueError: Column response does not exist in the training frame
gbm.train(
    x=predictor_columns,
    y=response_column,
    training_frame=training_frame,
    validation_frame=validation_frame)
```

**Comment by mmalohlava** [comment] 2018-01-23 20:54
Revisiting our solution, it seems like bug for me. We wanted to limit preview of data to 100cols, but we also limited list of column names and types. https://0xdata.atlassian.net/browse/PUBDEV-5179

**Comment by willfrey** [comment] 2018-01-24 14:56
Can you suggest a workaround for the time being?

**Comment by jakubhava** [comment] 2018-01-24 15:27
@willfrey sorry for delay, The workaround, in this case is to replace `h2oframe = hc.as_h2o_frame(dataframe)` with

```
from h2o.frame import H2OFrame
j_h2o_frame = hc._jhc.asH2OFrame(dataframe._jdf, None)
j_h2o_frame_key = j_h2o_frame.key()
h2oframe = H2OFrame.from_java_h2o_frame(j_h2o_frame, j_h2o_frame_key, j_h2o_frame.numCols())
```

Basically, we need to call the internal API manually, because right now, the settings of how many columns can be specified only there

**Comment by willfrey** [comment] 2018-01-25 17:39
Thank you!

**Comment by jakubhava** [comment] 2018-01-25 21:13
No worries, we already have a fix here for H2O https://0xdata.atlassian.net/browse/PUBDEV-5179 which will get into Sparkling Water as well. Let me close this issue for now and if you need more info, please check the Jira. 

Thanks again for reporting!

**Closed by jakubhava** 2018-01-25 21:13 UTC
