### ISSUE TITLE
ArrayIndexOutOfBoundsException while converting sparklyr dataframe to h2o dataframe and viceversa

### ISSUE THREAD

**Issue by yeshwanth43** [h2oai/sparkling-water#715] opened 2018-05-18 16:33 UTC
Version Information:
```
sparklyr version 0.6.3
rsparkling 0.2.1
dplyr  0.7.4
tidyr 0.6.3
Sparkling Water 2.0.1
Spark 2.0.0.cloudera2
```

we have 2 GB parquet dataset contains 10 Million rows and 190 columns
we are trying to run h2o models by reading the parquet as sparklyr dataframe and converting it to h2o dataframe, there we are hitting

```R
train_table <- as_h2o_frame(sc, partitions$training, strict_version_check = FALSE)
```
```java
java.lang.ArrayIndexOutOfBoundsException: 65535
      at water.DKV.get(DKV.java:204)
      at water.DKV.get(DKV.java:177)
      at water.Key.get(Key.java:84)
      at water.fvec.Frame.createNewChunks(Frame.java:920)
      at water.fvec.FrameUtils$class.createNewChunks(FrameUtils.scala:43)
      at water.fvec.FrameUtils$.createNewChunks(FrameUtils.scala:70)
      at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.createChunks(InternalWriteConverterCtx.scala:29)
      at org.apache.spark.h2o.converters.SparkDataFrameConverter$.org$apache$spark$h2o$converters$SparkDataFrameConverter$$perSQLPartition(SparkDataFrameConverter.scala:95)
      at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$2.apply(SparkDataFrameConverter.scala:74)
      at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$2.apply(SparkDataFrameConverter.scala:74)
      at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
      at org.apache.spark.scheduler.Task.run(Task.scala:86)
      at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748) 
```

Sparklyr application has h2o internal cluster 
following is the configuration of h2o and spaklyr

```R
sc <-
  spark_connect(master = "yarn-client", app_name = "sparklyr", version = "2.0.0",
                config = list(
                  spark.submit.deployMode = "client",
                  spark.executor.memory = "64G",
                  spark.executor.cores = 8,
                  spark.executor.instances = 8,
                  "spark.ext.h2o.cluster.size"="8",
                  "sparklyr.shell.driver-memory"="16G",
                  spark.dynamicAllocation.enabled="false"
                ))
#Get H20 Context, will create if one not present
tic("Get H2O Context")
h2o_context(sc)
toc()
```

for now we are doing workaround of reading and writing separately by using h2o import and export file api's

this issue is already reported at [597](https://github.com/h2oai/sparkling-water/issues/597)
what would be the problem here

**Comment by jakubhava** [comment] 2018-05-23 10:11
We need to see the logs to see what is happening. The Spark executor probably died, but would be good to see why. @yeshwanth43 could you please share your YARN logs?

**Comment by jakubhava** [comment] 2018-06-12 11:35
We can proceed without the logs, closing the issue. @yeshwanth43 if you will be able to upload the logs, please feel free to reopen the issue

**Closed by jakubhava** 2018-06-12 11:35 UTC

**Comment by pdurham2** [comment] 2020-03-06 16:32
I am unsure if this error was ever resolved, but I found that repartitioning the Spark dataframe with df.repartition() before converting to an H2O dataframe allowed the conversion to occur successfully.

**Comment by jakubhava** [comment] 2020-03-06 22:42
@pdurham2 We need logs, Sparkling Water version, Rsparkling version to be able to reason about whether it's a new bug or if it has been fixed in a newer version.

Thanks!

**Comment by pdurham2** [comment] 2020-03-12 15:40
@jakubhava, I originally was using h2o_pysparkling_2.4-2.4.2.zip but tested under sparkling-water-3.28.1.1-1-2.4 using Python 3.5 and Spark 2.4.3. I experienced the error with both versions of sparkling water, and repartitioning seemed to avoid the ArrayIndexOutOfBoundsException error. Regarding logs, I'm sorry but I don't think I am allowed to share them. Hopefully, the above info helps!

**Comment by jakubhava** [comment] 2020-03-12 21:45
Without logs It's hard to reason about the issue. Can you please share the minimal reproducible code example?

**Comment by jbentleyEG** [comment] 2020-06-06 06:11
I am having this issue on 3.30.0.3 using a Spark Standalone cluster rather than YARN. I was not able to solve by repartitioning.

Here is an excerpt from the Spark executor log:

`20/06/06 05:04:03 INFO H2OChunk: External H2O node http://10.101.0.89:54321/3/ChunkCategoricalDomains?frame_name=trainData2422fe37-1d92-4d09-9aa9-e4b046502c89&chunk_id=291&compression=SNAPPY successfully responded for the PUT.
20/06/06 05:04:03 INFO H2OChunk: External H2O node http://10.101.0.89:54321/3/ChunkCategoricalDomains?frame_name=trainData2422fe37-1d92-4d09-9aa9-e4b046502c89&chunk_id=291&compression=SNAPPY successfully responded for the PUT.
20/06/06 05:04:03 INFO Executor: Finished task 291.0 in stage 2088.0 (TID 86947). 1428 bytes result sent to driver
20/06/06 05:04:03 INFO H2OChunk: External H2O node http://10.101.0.89:54321/3/Chunk?frame_name=trainData2422fe37-1d92-4d09-9aa9-e4b046502c89&num_rows=1506&compression=SNAPPY&maximum_vector_sizes=&expected_types=CAcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwsABwcLCwsHCwcHBwcHCwsLCwcHBwcHCAsACwsJCQkEBwQLCQkHBwcHBwcHBwALBw%3D%3D&chunk_id=296 successfully responded for the PUT.
20/06/06 05:04:03 INFO H2OChunk: External H2O node http://10.101.0.89:54321/3/ChunkCategoricalDomains?frame_name=trainData2422fe37-1d92-4d09-9aa9-e4b046502c89&chunk_id=296&compression=SNAPPY successfully responded for the PUT.
20/06/06 05:04:03 INFO H2OChunk: External H2O node http://10.101.0.89:54321/3/ChunkCategoricalDomains?frame_name=trainData2422fe37-1d92-4d09-9aa9-e4b046502c89&chunk_id=296&compression=SNAPPY successfully responded for the PUT.
20/06/06 05:04:03 INFO Executor: Finished task 296.0 in stage 2088.0 (TID 86952). 1385 bytes result sent to driver`

I will have to re-run to get the h2o log, but there were no errors in it. Even though I get an exception, I can see the data frame in the Flow UI and build a model off of it. I did not have this issue previously with 3.28.0.1.

**Comment by jakubhava** [comment] 2020-06-08 06:24
@jbentleyEG You mentioned exception, can you share that exception?

**Comment by jbentleyEG** [comment] 2020-06-11 05:34
Yes, it's the same exception as above.

> Error: java.lang.ArrayIndexOutOfBoundsException: 65535
	at water.DKV.get(DKV.java:211)
	at water.DKV.get(DKV.java:184)
	at water.fvec.H2OFrame.<init>(H2OFrame.scala:61)
	at water.fvec.H2OFrame.<init>(H2OFrame.scala:69)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:218)

**Comment by jakubhava** [comment] 2020-06-11 06:13
This usually means that H2O is not running. Did you create H2OContext? Please share minimal reproducible example.

Thanks

**Comment by jbentleyEG** [comment] 2020-06-11 15:02
H2O is running, and the dataframe loads even though it throws an exception. I am able to get around it with this:

`val newH2OFrame: H2OFrame = try {
     myH2OContext.asH2OFrame(partitionedData, name)
    }
    catch {
      case e: ArrayIndexOutOfBoundsException => myH2OContext.asH2OFrame(name)
    }`

I'll see what I can do about a reproducible example, although it only happens on my production system. I'm running Spark as standalone in prod, in my tests where Spark runs in local mode everything works fine.

**Comment by jbentleyEG** [comment] 2020-06-22 17:41
Update: It looks like the root cause of this is that I am instantiating H2O/Sparkling Water in R and then passing the h2o$jhc object into Scala and then using it in Scala. This used to work, but apparently no longer does. If I instantiate H2O in Scala it works fine, but I then cannot also access it in R. This also seems to work fine in local mode, but not standalone. I don't know about YARN.

If you have some immediate intuition as to why this might be the case let me know, otherwise I will try to put together a minimum reproducible example and open a fresh JIRA ticket.

Thanks,
Jordan

**Comment by jakubhava** [comment] 2020-06-22 17:45
@jbentleyEG Are you using RSparkling in a way as mentioned on our documentation? If I remember correctly, you have some non-standard usage of RSparking via reflection? But I just remember that vaguely.

If it's the first case, we are really happy to support it as that would be a bug affecting more users. If you have any non-standard deployment, please just note that it is not a priority for us to make it work soon. We off-course welcome pull-requests from the community!

Hope it makes sense :)
