### ISSUE TITLE
Convert h2oframe to spark dataframe using rsparkling

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#1121] opened 2019-04-07 10:47 UTC
I can convert spark dataframe to h2oframe but not  h2oframe to sparkdataframe.
```
calls <- sc %>% tbl("default.calls")

calls <- calls %>% 
  filter(fecha_inicio == "20190406")

# it works to send a h2o cluster
calls_hex <- as_h2o_frame(sc, calls,"calls_hex")

# Fail get batk to spark
tmp_spark <- as_spark_dataframe(sc, calls_hex, name="tmp_spark" )
```
Error: java.lang.Exception: No matched method found for class org.apache.spark.h2o.H2OContext.asDataFrame

sessionInfo()
other attached packages:
[1] sparklyr_1.0.0    dplyr_0.8.0.1     h2o_3.24.0.1     
[4] rsparkling_0.2.22

**Comment by jakubhava** [comment] 2019-04-08 11:04
Hi @joscani I could not reproduce the issue.

Can you please share minimal & full reproducible code together with configurations options passed to RSparkling?

What Spark versions are you using, what Sparkling Water versions are you using? How are you starting RSparkling? Do you explicitly pass the jar file of Sparkling Water or do you let RSparkling to download the latest one?

Thanks

**Comment by hemanshupaliwa7** [comment] 2019-04-18 08:29
Is it solved ?? I am having the same issue..I have installed all the compatible versions of Spark, sparkling water and h2o, but still i get this error "Error: java.lang.Exception: No matched method found for class org.apache.spark.h2o.H2OContext.asDataFrame"

**Comment by jakubhava** [comment] 2019-04-18 08:54
@hemanshupaliwa7 which Spark & Sparkling Water & H2O versions are you using? Please also share reproducible code, that will help us debug the issue. Thank you! 

Kuba

**Comment by hemanshupaliwa7** [comment] 2019-04-18 09:52
R -> 3.5.3
Spark -> 2.3.0
Sparkling Water -> 2.3.23
H2O -> 3.22.1.3
As per the compatibility shown here, I ahve all of them correctly installed -> http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/rsparkling.html

I am using code from https://spark.rstudio.com/guides/h2o/

My code looks like this :-
```

Sys.unsetenv("https_proxy")
Sys.unsetenv("http_proxy")

library(rsparkling)
library(sparklyr)
library(h2o)

h2o.init()

sc <- spark_connect(master = "local")

h2o_context(sc)

library(dplyr)

mtcars_tbl1 <- copy_to(sc, mtcars, overwrite = TRUE)

mtcars_hf <- as_h2o_frame(sc, mtcars_tbl1)

y <- "mpg"
x <- setdiff(names(mtcars_hf), y)

splits <- h2o.splitFrame(mtcars_hf, ratios = 0.7, seed = 1)

fit <- h2o.gbm(x = x,
               y = y,
               training_frame = splits[[1]],
               nfolds = 3,
               min_rows = 1,
               seed = 1)
print(fit)


mtcars_tbl <- copy_to(sc, mtcars, overwrite = TRUE)

partitions <- mtcars_tbl %>%
  filter(hp >= 100) %>%
  mutate(cyl8 = cyl == 8) %>%
  sdf_partition(training = 0.5, test = 0.5, seed = 1099)

training <- as_h2o_frame(sc, partitions$training, strict_version_check = FALSE)
test <- as_h2o_frame(sc, partitions$test, strict_version_check = FALSE)

# fit a linear model to the training dataset
glm_model <- h2o.glm(x = c("wt", "cyl"), 
                     y = "mpg", 
                     training_frame = training,
                     lambda_search = TRUE)

glm_model

library(ggplot2)

# compute predicted values on our test dataset
pred <- h2o.predict(glm_model, newdata = test)
# convert from H2O Frame to Spark DataFrame
predicted <- as_spark_dataframe(sc, pred, strict_version_check = FALSE) ##Fails here

```
Error I get when i execute the last line of the code:
```
> predicted <- as_spark_dataframe(sc, pred, strict_version_check = FALSE) ##Fails here
Error: java.lang.Exception: No matched method found for class org.apache.spark.h2o.H2OContext.asDataFrame
	at sparklyr.Invoke.invoke(invoke.scala:136)
	at sparklyr.StreamHandler.handleMethodCall(stream.scala:123)
	at sparklyr.StreamHandler.read(stream.scala:66)
	at sparklyr.BackendHandler.channelRead0(handler.scala:51)
	at sparklyr.BackendHandler.channelRead0(handler.scala:4)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jakubhava** [comment] 2019-04-18 09:52
Thank you @hemanshupaliwa7, we will have a look!

**Comment by hemanshupaliwa7** [comment] 2019-04-24 05:54
@jakubhava anything my friend?

**Comment by jakubhava** [comment] 2019-04-24 12:28
@hemanshupaliwa7 I see a bad Sparkling Water pattern in your code which is causing your issue

I see that you call `h2o.init()`. This code should not be run in Sparkling Water environment. It checks whether H2O is running and if not, it starts it locally. However without Sparkling Water dependencies and connection. You should just call `h2o_context(sc)` which internally calls `h2o.init()` on the right place.

The sufficient code to start with is 

```
library(rsparkling)
library(sparklyr)
sc <- spark_connect(master = "local")
h2o_context(sc)
```

Also please have a look on the http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/rsparkling.html

**Comment by jakubhava** [comment] 2019-04-24 13:56
Also, @hemanshupaliwa7 @joscani we have found the bug and fixed in the current master of Sparkling Water.

We are planning to do release soon which will have this fixed. You will need to update RSparkling to the latest version

**Comment by jakubhava** [comment] 2019-04-25 11:46
Release will be done today, please check our download page tomorrow to get the version with fixed RSParkling & Sparkling Water

**Closed by jakubhava** 2019-04-25 11:46 UTC

**Comment by hemanshupaliwa7** [comment] 2019-04-25 12:33
Thanks @jakubhava ...Can you please share the download page link? If possible :)

**Comment by jakubhava** [comment] 2019-04-25 12:48
www.h2o.ai

**Comment by joscani** [comment] 2019-05-03 10:20
Thanks @jakubhava

**Comment by hemanshupaliwa7** [comment] 2019-05-03 11:58
> https://h2o.ai -> Downloads -> Select Sparkling Water for your Spark

Thanks @jakubhava ..It's working now :)

**Comment by hemanshupaliwa7** [comment] 2019-12-10 11:49
Hello @jakubhava... Hope you are doing good!!

I bring another issue of the same topic Spark DF to H2O Df in scala

I am following this notebook https://docs.databricks.com/_static/notebooks/h2o-sparkling-water-scala.html
And i get this error when I am converting spark dataframe to h2o

`[error] (run-main-0) java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
java.lang.NoSuchMethodError: jsr166y.CountedCompleter.quietlyComplete()V
	at jsr166y.CountedCompleter.__tryComplete(CountedCompleter.java:427)
	at jsr166y.CountedCompleter.tryComplete(CountedCompleter.java:383)
	at water.Atomic.compute2(Atomic.java:78)
	at water.Atomic.fork(Atomic.java:39)
	at water.Atomic.invoke(Atomic.java:31)
	at water.Lockable.write_lock(Lockable.java:61)
	at water.Lockable.delete_and_lock(Lockable.java:70)
	at water.Lockable.delete_and_lock(Lockable.java:67)
	at water.fvec.Frame.preparePartialFrame(Frame.java:1044)
	at water.fvec.FrameUtils$class.preparePartialFrame(FrameUtils.scala:30)
	at water.fvec.FrameUtils$.preparePartialFrame(FrameUtils.scala:72)
	at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.initFrame(InternalWriteConverterCtx.scala:43)
	at org.apache.spark.h2o.converters.WriteConverterCtxUtils$.convert(WriteConverterCtxUtils.scala:85)
	at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:81)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:215)
	at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:215)
	at org.apache.spark.h2o.utils.H2OContextUtils$class.withConversionDebugPrints(H2OContextUtils.scala:89)
	at org.apache.spark.h2o.H2OContext.withConversionDebugPrints(H2OContext.scala:64)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:215)
	at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:212)
	at analyticsvidya.loanprediction3.H2OMain$.delayedEndpoint$com$vodafone$aquaduct$core$analyticsvidya$loanprediction3$H2OMain$1(H2OMain.scala:34)
	at analyticsvidya.loanprediction3.H2OMain$delayedInit$body.apply(H2OMain.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:383)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at analyticsvidya.loanprediction3.H2OMain$.main(H2OMain.scala:7)
	at analyticsvidya.loanprediction3.H2OMain.main(H2OMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppress`

**Comment by jakubhava** [comment] 2019-12-10 13:24
@joscani can you please share information about your environment and versions?
